name: Continuous integration
on:
  pull_request:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
  node-setup:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: nodejs setup
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
  Compile:
    runs-on: ubuntu-latest
    needs: node-setup
    steps:
      - name: compiling code
        run: npm run compile

  testing:
    runs-on: ubuntu-latest
    needs: Compile
    steps:
      - name: Testing at first stage
        run: npm run test
  linting:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Linting for code
        run: npm run lint