name: Continuous integration
on:
  pull_request:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
  node-setup:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: nodejs setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

      - name: compiling code
        run: npm run compile

      - name: Testing at first stage
        run: npm run test
      - name: Linting for code
        run: npm run lint